import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-client-list',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './client-list.component.html',
})
export class ClientListComponent {
  clients = [
    {
      id: 1,
      nombre: 'Juan',
      apellidos: 'García López',
      email: 'juan.garcia@gmail.com',
      telefono: '612345678',
      direccion: 'Calle Mayor 12',
      ciudad: 'Madrid',
      provincia: 'Madrid',
      fechaRegistro: '2025-05-20T10:30:00Z',
    },
    {
      id: 2,
      nombre: 'Laura',
      apellidos: 'Pérez Gómez',
      email: 'laura.perez@gmail.com',
      telefono: '698765432',
      direccion: 'Avda. de la Paz 101',
      ciudad: 'Sevilla',
      provincia: 'Sevilla',
      fechaRegistro: '2025-05-19T09:15:00Z',
    },
    {
      id: 3,
      nombre: 'Carlos',
      apellidos: 'Martínez Ruiz',
      email: 'carlos.mr@yahoo.es',
      telefono: '600112233',
      direccion: 'Calle Falsa 123',
      ciudad: 'Valencia',
      provincia: 'Valencia',
      fechaRegistro: '2025-05-18T14:45:00Z',
    },
    {
      id: 4,
      nombre: 'Ana',
      apellidos: 'Torres Sánchez',
      email: 'ana.torres@hotmail.com',
      telefono: '611223344',
      direccion: 'Plaza del Sol 7',
      ciudad: 'Barcelona',
      provincia: 'Barcelona',
      fechaRegistro: '2025-05-17T17:00:00Z',
    },
    {
      id: 5,
      nombre: 'Luis',
      apellidos: 'Ramírez Díaz',
      email: 'luis.ramirez@gmail.com',
      telefono: '633445566',
      direccion: 'Calle Luna 15',
      ciudad: 'Bilbao',
      provincia: 'Vizcaya',
      fechaRegistro: '2025-05-16T08:30:00Z',
    },
    {
      id: 6,
      nombre: 'Sofía',
      apellidos: 'Moreno Blanco',
      email: 'sofia.moreno@gmail.com',
      telefono: '644556677',
      direccion: 'Avda. del Mar 8',
      ciudad: 'Málaga',
      provincia: 'Málaga',
      fechaRegistro: '2025-05-15T13:20:00Z',
    },
    {
      id: 7,
      nombre: 'Daniel',
      apellidos: 'Navarro Cruz',
      email: 'daniel.ncruz@gmail.com',
      telefono: '655667788',
      direccion: 'Calle Nueva 33',
      ciudad: 'Alicante',
      provincia: 'Alicante',
      fechaRegistro: '2025-05-14T11:50:00Z',
    },
    {
      id: 8,
      nombre: 'María',
      apellidos: 'Santos León',
      email: 'maria.santos@outlook.com',
      telefono: '666778899',
      direccion: 'Calle Castilla 4',
      ciudad: 'Toledo',
      provincia: 'Toledo',
      fechaRegistro: '2025-05-13T15:40:00Z',
    },
    {
      id: 9,
      nombre: 'Pablo',
      apellidos: 'Herrera Gil',
      email: 'pablo.hg@gmail.com',
      telefono: '677889900',
      direccion: 'Camino Viejo 22',
      ciudad: 'Granada',
      provincia: 'Granada',
      fechaRegistro: '2025-05-12T10:25:00Z',
    },
    {
      id: 10,
      nombre: 'Carmen',
      apellidos: 'Flores Peña',
      email: 'carmen.flores@gmail.com',
      telefono: '688990011',
      direccion: 'Calle Jardín 3',
      ciudad: 'Zaragoza',
      provincia: 'Zaragoza',
      fechaRegistro: '2025-05-11T12:00:00Z',
    },
    {
      id: 11,
      nombre: 'Andrés',
      apellidos: 'Ortega Vargas',
      email: 'andres.ortega@gmail.com',
      telefono: '699001122',
      direccion: 'Paseo del Río 18',
      ciudad: 'Salamanca',
      provincia: 'Salamanca',
      fechaRegistro: '2025-05-10T09:10:00Z',
    },
    {
      id: 12,
      nombre: 'Patricia',
      apellidos: 'Núñez Ramos',
      email: 'patricia.nunez@gmail.com',
      telefono: '611223355',
      direccion: 'Calle Norte 5',
      ciudad: 'Cádiz',
      provincia: 'Cádiz',
      fechaRegistro: '2025-05-09T16:30:00Z',
    },
    {
      id: 13,
      nombre: 'Javier',
      apellidos: 'López Díaz',
      email: 'javier.ld@gmail.com',
      telefono: '622334466',
      direccion: 'Avda. del Sur 6',
      ciudad: 'Huelva',
      provincia: 'Huelva',
      fechaRegistro: '2025-05-08T13:00:00Z',
    },
    {
      id: 14,
      nombre: 'Lucía',
      apellidos: 'Ruiz Morales',
      email: 'lucia.ruiz@gmail.com',
      telefono: '633445577',
      direccion: 'Calle Central 2',
      ciudad: 'Murcia',
      provincia: 'Murcia',
      fechaRegistro: '2025-05-07T11:25:00Z',
    },
    {
      id: 15,
      nombre: 'Miguel',
      apellidos: 'Suárez Campos',
      email: 'miguel.suarez@gmail.com',
      telefono: '644556688',
      direccion: 'Calle Estación 9',
      ciudad: 'León',
      provincia: 'León',
      fechaRegistro: '2025-05-06T10:45:00Z',
    },
    {
      id: 16,
      nombre: 'Isabel',
      apellidos: 'Jiménez Herrera',
      email: 'isabel.jimenez@gmail.com',
      telefono: '655667799',
      direccion: 'Calle Real 1',
      ciudad: 'Logroño',
      provincia: 'La Rioja',
      fechaRegistro: '2025-05-05T15:00:00Z',
    },
    {
      id: 17,
      nombre: 'Raúl',
      apellidos: 'Molina Díaz',
      email: 'raul.molina@gmail.com',
      telefono: '666778800',
      direccion: 'Camino de Santiago 8',
      ciudad: 'Santiago',
      provincia: 'La Coruña',
      fechaRegistro: '2025-05-04T17:20:00Z',
    },
    {
      id: 18,
      nombre: 'Eva',
      apellidos: 'Castro Méndez',
      email: 'eva.castro@gmail.com',
      telefono: '677889911',
      direccion: 'Calle Sur 14',
      ciudad: 'Oviedo',
      provincia: 'Asturias',
      fechaRegistro: '2025-05-03T09:35:00Z',
    },
    {
      id: 19,
      nombre: 'Tomás',
      apellidos: 'Gil Torres',
      email: 'tomas.gil@gmail.com',
      telefono: '688990022',
      direccion: 'Avda. Libertad 11',
      ciudad: 'Pamplona',
      provincia: 'Navarra',
      fechaRegistro: '2025-05-02T14:10:00Z',
    },
    {
      id: 20,
      nombre: 'Marta',
      apellidos: 'Cano Vidal',
      email: 'marta.cano@gmail.com',
      telefono: '699001133',
      direccion: 'Calle Esperanza 7',
      ciudad: 'Burgos',
      provincia: 'Burgos',
      fechaRegistro: '2025-05-01T11:50:00Z',
    },
  ];
}
